INSERT INTO ADDRESS(ID, STREET, POST_CODE, CITY) VALUES (1, 'test', '33-241', 'Warszawa');
INSERT INTO ADDRESS(ID, STREET, POST_CODE, CITY) VALUES (2, 'test2', '60-777', 'Poznan');

INSERT INTO PATIENT(ID, FIRST_NAME, LAST_NAME, ADDRESS_ID) VALUES (1, 'Zbigniew', 'Kowalski',1);
INSERT INTO PATIENT(ID, FIRST_NAME, LAST_NAME, ADDRESS_ID) VALUES (2, 'Jan', 'Nowak',2);